import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import AuthProvider from '@/components/auth-provider';
import Header from '@/components/header';
import Sidebar from '@/components/sidebar';
import { Card, CardContent } from '@/components/ui/card';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + ' dark p-4'}>
                <AuthProvider>
                    <Sidebar />
                    <Card className="ml-[calc(30vw+1rem)]">
                        <CardContent className="flex flex-col gap-10">
                            <Header />
                            {children}
                        </CardContent>
                    </Card>
                </AuthProvider>
            </body>
        </html>
    );
}
