import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import Header from "@/components/header";
import Player from "@/components/player/player";
import Providers from "@/components/providers/providers";
import Sidebar from "@/components/sidebar";
import { Card, CardContent } from "@/components/ui/card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} dark p-4`}>
                <Providers>
                    <div className="flex flex-col-reverse">
                        <Player />
                        <Sidebar />
                        <Card className="mb-[148px] min-h-[calc(100vh-148px-2rem)] sm:mb-[80px] sm:ml-[calc(30vw+1rem)] sm:min-h-[calc(100vh-80px-2rem)]">
                            <CardContent className="flex flex-col gap-4">
                                <Header />
                                {children}
                            </CardContent>
                        </Card>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
